# Generated by Django 5.1.3 on 2024-11-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('perfil', models.CharField(choices=[('Administrador', 'Administrador'), ('Professor', 'Professor'), ('Aluno', 'Aluno')], max_length=15)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
